baseURL = "https://xsteave.github.io/"
languageCode = "en-us"
title = "Steave Portfolio"
theme = "somrat"

# Pagination fix pour Hugo >=0.128
[pagination]
  pagerSize = 6

# Autres paramètres de ton site
[params]
  custom_css = ""
  custom_class = ""
  custom_attributes = ""